# Generated by Django 4.0.5 on 2022-07-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vocab_Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('delete', models.BooleanField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluency.vocablist')),
            ],
        ),
    ]
